# Generated by Django 4.1 on 2023-01-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skillers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('special_skill', models.CharField(max_length=100)),
                ('skill_decs', models.CharField(max_length=1000)),
            ],
        ),
    ]
