# Generated by Django 4.1.5 on 2023-01-17 13:38

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_contact_no',
            field=phone_field.models.PhoneField(blank=True, max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=phone_field.models.PhoneField(max_length=31, unique=True),
        ),
    ]
