# Generated by Django 4.1.5 on 2023-01-17 13:39

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillersApp', '0002_alter_user_business_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_contact_no',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
