# Generated by Django 4.1.5 on 2023-01-29 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SkillersApp', '0004_alter_user_business_contact_no_alter_user_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectStatus', models.PositiveSmallIntegerField(choices=[(3, 'completed'), (2, 'pending'), (1, 'started'), (0, 'searching')], default=0)),
                ('projectBudget', models.FloatField(default=0, verbose_name='Project Budget')),
            ],
            options={
                'verbose_name': 'clientmodel',
                'verbose_name_plural': 'clientmodels',
            },
        ),
        migrations.CreateModel(
            name='Skiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=20, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'tags',
                'verbose_name_plural': 'tagss',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='business_contact_no',
            field=models.CharField(max_length=12, verbose_name='Contact number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.CharField(max_length=12),
        ),
        migrations.CreateModel(
            name='SkliierPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillTitle', models.CharField(max_length=50, verbose_name='Title')),
                ('SkillImage', models.ImageField(null=True, upload_to='upload/skillImages', verbose_name='Skill Image')),
                ('SkillDescription', models.CharField(max_length=1200, verbose_name='Description')),
                ('SkillerWages', models.FloatField(null=True, verbose_name='Avg Wages Rate')),
                ('skillerContact', models.CharField(max_length=12, null=True, verbose_name='Contact number')),
                ('skillerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillersApp.skiller', verbose_name='pk')),
            ],
            options={
                'verbose_name': 'skliierpost',
                'verbose_name_plural': 'skliierposts',
            },
        ),
        migrations.AddField(
            model_name='skiller',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillersApp.user', verbose_name='pk'),
        ),
        migrations.CreateModel(
            name='ProjectRequestModel',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('projectDesc', models.CharField(max_length=1200, verbose_name='Project desvription')),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillersApp.clientmodel', verbose_name='Client ID')),
                ('skillerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillersApp.skiller', verbose_name='Skiller ID')),
                ('tagModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillersApp.tags', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillersApp.user', verbose_name='pk'),
        ),
    ]
