# Generated by Django 4.1.5 on 2023-01-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillersApp', '0005_clientmodel_skiller_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='projectStatus',
            field=models.PositiveSmallIntegerField(choices=[(1, 'started'), (3, 'completed'), (2, 'pending'), (0, 'searching')], default=0),
        ),
    ]
